name: Waving Cosmonauts Raffle

on:
  schedule:
    - cron: "0 17 * * 0"

jobs:
  raffle:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up python environment
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.10"
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Launch raffle
      run: |
        python raffle.py
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update weekly raffle winner file
        file_pattern: data/winner_variables.json
