name: raffle

# TODO update this for a specific week day / time
on: [push, pull_request]

jobs:
  raffle:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up python environment
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.10"
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Launch raffle
      run: |
        python raffle.py
    - name: Git information
      run: |
        pwd
        git diff
        git branch
    # - name: Commit last winner to data file
    #   run:
    #     git config --local user.email "cosmonautnft@users.noreply.github.com"
    #     git config --local user.name "cosmonautnft gh bot"
    #     git add .
    #     git commit -a -m "Update last winner on '$(date)'"
