name: Waving Cosmonauts Raffle

on:
  schedule:
  # - cron: "0 17 * * 7"
    - cron: "0 12 * * 2"

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up python environment
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.10"
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
    - name: Launch raffle
      run: |
        python raffle.py
